// AISmokeShaqStudio/models/index.js

export const MODELS = {
  image: [
    {
      id: 'black-forest-labs/flux-2-pro',
      name: 'FLUX.2 Pro',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'black-forest-labs/flux-2-flex',
      name: 'FLUX.2 Flex',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'bytedance/seedream-4.5',
      name: 'Seedream 4.5',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'bytedance/seedream-5-lite',
      name: 'Seedream 5 Lite',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'bytedance/seedream-3',
      name: 'Seedream 3',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'google/imagen-4-ultra',
      name: 'Imagen 4 Ultra',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 4,
    },
    {
      id: 'wan-video/wan-2.7-image-pro',
      name: 'WAN 2.7 Image Pro',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'ideogram-ai/ideogram-v3-turbo',
      name: 'Ideogram V3 Turbo',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'ideogram-ai/ideogram-v2',
      name: 'Ideogram V2',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'minimax/image-01',
      name: 'MiniMax Image-01',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'comfyui/any-comfyui-workflow',
      name: 'Any ComfyUI Workflow',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'fermatresearch/sdxl-controlnet-lora',
      name: 'SDXL ControlNet LoRA',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'lucataco/ssd-1b',
      name: 'SSD-1B',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },

    // Hugging Face NSFW image/video models (visible but locked)
    {
      id: 'imb101/I2V-WAN2.2-POVFaceSitting',
      name: 'I2V WAN 2.2 POV Face Sitting',
      provider: 'huggingface',
      nsfw: true,
      locked: true,
      credits: 4,
    },
    {
      id: 'gooniebloans/igoonhard',
      name: 'iGoonHard',
      provider: 'huggingface',
      nsfw: true,
      locked: true,
      credits: 4,
    },
    {
      id: 'Jonny001/NSFW_master',
      name: 'NSFW Master',
      provider: 'huggingface',
      nsfw: true,
      locked: true,
      credits: 4,
    },
  ],

  video: [
    {
      id: 'runwayml/gen-4.5',
      name: 'Runway Gen-4.5',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 5,
    },
    {
      id: 'google/veo-3.1',
      name: 'Google VEO 3.1',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 5,
    },
    {
      id: 'google/veo-2',
      name: 'Google VEO 2',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 4,
    },
    {
      id: 'kwaivgi/kling-v3-video',
      name: 'Kling V3 Video',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 4,
    },
    {
      id: 'kwaivgi/kling-v3-omni-video',
      name: 'Kling V3 Omni Video',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 4,
    },
    {
      id: 'kwaivgi/kling-v2.0',
      name: 'Kling V2.0',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'kwaivgi/kling-v2.5-turbo-pro',
      name: 'Kling V2.5 Turbo Pro',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 4,
    },
    {
      id: 'bytedance/seedance-2.0',
      name: 'Seedance 2.0',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 4,
    },
    {
      id: 'bytedance/seedance-1.5-pro',
      name: 'Seedance 1.5 Pro',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 4,
    },
    {
      id: 'bytedance/seedance-1-lite',
      name: 'Seedance 1 Lite',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'bytedance/seedance-1-pro',
      name: 'Seedance 1 Pro',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'xai/grok-imagine-video',
      name: 'Grok Imagine Video',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 4,
    },
    {
      id: 'minimax/hailuo-2.3',
      name: 'Hailuo 2.3',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 4,
    },
    {
      id: 'minimax/video-01',
      name: 'MiniMax Video-01',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'wan-video/wan-2.7-t2v',
      name: 'WAN 2.7 T2V',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 4,
    },
    {
      id: 'wan-video/wan-2.5-t2v-fast',
      name: 'WAN 2.5 T2V Fast',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'wan-video/wan-2.2-t2v-fast',
      name: 'WAN 2.2 T2V Fast',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'wan-video/wan-2.5-i2v-fast',
      name: 'WAN 2.5 I2V Fast',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'wan-video/wan-2.2-s2v',
      name: 'WAN 2.2 S2V',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'prunaai/p-video',
      name: 'P-Video',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'prunaai/p-video-animate',
      name: 'P-Video Animate',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'prunaai/p-video-avatar',
      name: 'P-Video Avatar',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'alibaba/happyhorse-1.0',
      name: 'HappyHorse 1.0',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'veed/fabric-1.0',
      name: 'VEED Fabric 1.0',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'bytedance/dreamactor-m2.0',
      name: 'DreamActor M2.0',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 4,
    },
    {
      id: 'fofr/tooncrafter',
      name: 'ToonCrafter',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
  ],

  tts: [
    {
      id: 'elevenlabs/v3',
      name: 'ElevenLabs v3',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'elevenlabs/turbo-v2.5',
      name: 'ElevenLabs Turbo v2.5',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'inworld/realtime-tts-2',
      name: 'Inworld Realtime TTS-2',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'minimax/speech-2.8-hd',
      name: 'MiniMax Speech 2.8 HD',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'minimax/speech-2.8-turbo',
      name: 'MiniMax Speech 2.8 Turbo',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'google/gemini-3.1-flash-tts',
      name: 'Gemini 3.1 Flash TTS',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'resemble-ai/chatterbox',
      name: 'Resemble Chatterbox',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'afiaka87/tortoise-tts',
      name: 'Tortoise TTS',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 2,
    },

    // Hugging Face TTS
    {
      id: 'fermatresearch/spanish-f5-tts',
      name: 'Spanish F5 TTS',
      provider: 'huggingface',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'x-lance/f5-tts',
      name: 'F5 TTS',
      provider: 'huggingface',
      nsfw: false,
      locked: false,
      credits: 2,
    },
    {
      id: 'chenxwh/openvoice',
      name: 'OpenVoice',
      provider: 'huggingface',
      nsfw: false,
      locked: false,
      credits: 2,
    },
  ],

  lipsync: [
    {
      id: 'pixverse/lipsync',
      name: 'PixVerse LipSync',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'sync/lipsync-2-pro',
      name: 'Sync LipSync-2 Pro',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'heygen/lipsync-speed',
      name: 'HeyGen LipSync Speed',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'heygen/lipsync-precision',
      name: 'HeyGen LipSync Precision',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'kwaivgi/kling-lip-sync',
      name: 'Kling Lip Sync',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'sync/react-1',
      name: 'Sync React-1',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'chenxwh/video-retalking',
      name: 'Video Retalking',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'wan-video/wan-2.2-s2v',
      name: 'WAN 2.2 S2V',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'zsxkib/multitalk',
      name: 'MultiTalk',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'xai/grok-imagine-video',
      name: 'Grok Imagine Video (Lipsync)',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 4,
    },
    {
      id: 'lucataco/stable-avatar',
      name: 'Stable Avatar',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'lightricks/audio-to-video',
      name: 'Lightricks Audio-to-Video',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },
    {
      id: 'bytedance/seedance-1.5-pro',
      name: 'Seedance 1.5 Pro (Lipsync)',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 4,
    },
    {
      id: 'prunaai/p-video-avatar',
      name: 'P-Video Avatar',
      provider: 'replicate',
      nsfw: false,
      locked: false,
      credits: 3,
    },

    // Hugging Face lipsync / avatar
    {
      id: 'ajwestfield/MeiGen-MultiTalk',
      name: 'MeiGen MultiTalk',
      provider: 'huggingface',
      nsfw: false,
      locked: false,
      credits: 3,
    },
  ],
};
